# Generated by Django 5.2.11 on 2026-08-13 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zellit_actor',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('square_feet', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year_built', models.PositiveSmallIntegerField()),
                ('listed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'zellit_listing',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.actor')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.listing')),
            ],
            options={
                'db_table': 'zellit_comment',
            },
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.CharField(max_length=32)),
                ('generator_version', models.CharField(max_length=32)),
                ('seed', models.PositiveBigIntegerField()),
                ('dataset_digest', models.CharField(max_length=64)),
                ('row_counts', models.JSONField()),
                ('generated_at', models.DateTimeField()),
                ('loaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'zellit_dataset_metadata',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='dataset_metadata_singleton')],
            },
        ),
        migrations.CreateModel(
            name='ListingVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_votes', to='listings.actor')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='listings.listing')),
            ],
            options={
                'db_table': 'zellit_listing_vote',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('position', models.PositiveSmallIntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'db_table': 'zellit_photo',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('population', models.PositiveIntegerField()),
                ('households', models.PositiveIntegerField()),
                ('median_age', models.PositiveSmallIntegerField()),
                ('median_household_income', models.PositiveIntegerField()),
                ('median_home_value', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'zellit_zip_code',
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9]{5}$')), name='zip_code_ascii_digits'), models.CheckConstraint(condition=models.Q(('state__regex', '^[A-Z]{2}$')), name='zip_state_upper_ascii'), models.CheckConstraint(condition=models.Q(('population__gte', 0), ('households__gte', 0), ('median_age__gte', 0), ('median_household_income__gte', 0), ('median_home_value__gte', 0)), name='zip_demographics_nonnegative')],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.zipcode'),
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='listings.actor')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='listings.comment')),
            ],
            options={
                'db_table': 'zellit_comment_vote',
                'constraints': [models.CheckConstraint(condition=models.Q(('value__in', (-1, 1))), name='comment_vote_value'), models.UniqueConstraint(fields=('comment', 'actor'), name='comment_vote_actor_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['listing', 'id'], name='comment_listing_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', (-1, 1))), name='listing_vote_value'),
        ),
        migrations.AddConstraint(
            model_name='listingvote',
            constraint=models.UniqueConstraint(fields=('listing', 'actor'), name='listing_vote_actor_unique'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(fields=('listing', 'position'), name='photo_listing_position_unique'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['zip_code', 'id'], name='listing_zip_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='listing_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms__gte', 0)), name='listing_bedrooms_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('bathrooms__gte', 0)), name='listing_bathrooms_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('square_feet__gt', 0)), name='listing_sqft_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('year_built__gte', 1600), ('year_built__lte', 2100)), name='listing_year_range'),
        ),
    ]
