"""create zellit schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-21 19:24:31.128087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zellit_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('zellit_dataset_metadata',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('dataset_digest', sa.String(length=64), nullable=False),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='dataset_metadata_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zellit_zip_code',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('households', sa.Integer(), nullable=False),
    sa.Column('median_age', sa.SmallInteger(), nullable=False),
    sa.Column('median_household_income', sa.Integer(), nullable=False),
    sa.Column('median_home_value', sa.Integer(), nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{5}$'", name='zip_code_ascii_digits'),
    sa.CheckConstraint("state ~ '^[A-Z]{2}$'", name='zip_state_upper_ascii'),
    sa.CheckConstraint('population >= 0 AND households >= 0 AND median_age >= 0 AND median_household_income >= 0 AND median_home_value >= 0', name='zip_demographics_nonnegative'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('zellit_listing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zip_code_id', sa.String(length=5), nullable=False),
    sa.Column('street_address', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.SmallInteger(), nullable=False),
    sa.Column('bathrooms', sa.SmallInteger(), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=False),
    sa.Column('year_built', sa.SmallInteger(), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bathrooms >= 0', name='listing_bathrooms_gte_0'),
    sa.CheckConstraint('bedrooms >= 0', name='listing_bedrooms_gte_0'),
    sa.CheckConstraint('price > 0', name='listing_price_gt_0'),
    sa.CheckConstraint('square_feet > 0', name='listing_sqft_gt_0'),
    sa.CheckConstraint('year_built >= 1600 AND year_built <= 2100', name='listing_year_range'),
    sa.ForeignKeyConstraint(['zip_code_id'], ['zellit_zip_code.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('listing_zip_id_idx', 'zellit_listing', ['zip_code_id', 'id'], unique=False)
    op.create_table('zellit_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['zellit_actor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['zellit_listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comment_listing_id_idx', 'zellit_comment', ['listing_id', 'id'], unique=False)
    op.create_table('zellit_listing_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='listing_vote_value'),
    sa.ForeignKeyConstraint(['actor_id'], ['zellit_actor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['zellit_listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'actor_id', name='listing_vote_actor_unique')
    )
    op.create_table('zellit_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['zellit_listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'position', name='photo_listing_position_unique')
    )
    op.create_table('zellit_comment_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='comment_vote_value'),
    sa.ForeignKeyConstraint(['actor_id'], ['zellit_actor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['zellit_comment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'actor_id', name='comment_vote_actor_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zellit_comment_vote')
    op.drop_table('zellit_photo')
    op.drop_table('zellit_listing_vote')
    op.drop_index('comment_listing_id_idx', table_name='zellit_comment')
    op.drop_table('zellit_comment')
    op.drop_index('listing_zip_id_idx', table_name='zellit_listing')
    op.drop_table('zellit_listing')
    op.drop_table('zellit_zip_code')
    op.drop_table('zellit_dataset_metadata')
    op.drop_table('zellit_actor')
    # ### end Alembic commands ###
